import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import StartingPage from '../components/StartingPage';
import { useEffect, useState } from 'react';
import FoodProduct from '../components/FoodProduct';
import { UserStore } from '../userStore';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { user, setUser } = UserStore.useContainer();
  const [localStorageContent, setLocalStorageContent] = useState(false);
  console.log(user); 
  useEffect(() => {
    const localStorageUser = JSON.parse(localStorage.getItem('user'));
    localStorageUser ? setLocalStorageContent(true) : setLocalStorageContent(false);
  }, [user])

  return (
    <>
      <Head>
        <title>Restaurant App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"
/>
      </Head>
      <main className=''>
        {
          localStorageContent || user ? <FoodProduct></FoodProduct> : <StartingPage></StartingPage>
        }
        <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
      </main>
    </>
  )
}
